#!/usr/bin/python3
##
# Manualmatic Pendant component for LinuxCNC.
#
# Sets up hal, linuxcnc, creates the Manualmatic helper class instance
# then connects to the Manulamatic Pendant over the USB PORT and starts 
# the poll()ing of the linuscnc user space interface.
#
# 
##

import sys
import time
import hal
import linuxcnc

from Jamcnccont import Jamcnccont, SerialFramer


c = hal.component("jamcnccont")

c.newpin("estop-is-activated", hal.HAL_BIT, hal.HAL_OUT)

jc = Jamcnccont(linuxcnc, hal, c, SerialFramer)

try:
  c.ready()
  jc.start()
except(KeyboardInterrupt):
  jc.stop()
  sys.exit(1)

except Exception as e:
  print("Exception in jamcnccont component")
  print(e)
  raise
  sys.exit(1)

